In [3]:
import numpy as np

ar1 = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

arr = np.array(ar1)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
print(arr[-1])

[ 8  9 10 11]


In [7]:
print(arr[1:])

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
print(arr[1:2])

[[4 5 6 7]]


In [10]:
print(arr[:-1])

[[0 1 2 3]
 [4 5 6 7]]
