您的代码实现了Softmax函数，但有一些可以改进和优化的地方。让我为您提供一个更完善和数值稳定的版本。

## 原始代码分析

您的代码基本正确，但有几个小问题：
1. 直接使用`math.exp()`处理numpy数组不够高效
2. 缺少数值稳定性处理（对于大数值容易溢出）
3. 打印语句较多，适合调试但不适合生产

## 改进版本

```python
import numpy as np

def softmax(X):
    """
    计算Softmax函数
    
    参数:
    X: 输入向量或矩阵
    
    返回:
    Softmax计算结果
    """
    # 数值稳定性处理：减去最大值防止指数溢出
    X_shifted = X - np.max(X)
    
    # 计算指数
    exp_values = np.exp(X_shifted)
    
    # 计算softmax
    softmax_output = exp_values / np.sum(exp_values)
    
    return softmax_output

# 测试
X = np.array([2, 1, 3, 5, 6])
print("输入向量:", X)

result = softmax(X)
print("Softmax结果:", result)
print("结果总和:", np.sum(result))  # 应该等于1

# 验证数值稳定性
print("\n=== 数值稳定性测试 ===")
large_X = np.array([1000, 1001, 1002])
print("大数值输入:", large_X)
print("稳定Softmax结果:", softmax(large_X))
print("稳定Softmax总和:", np.sum(softmax(large_X)))
```

## 批量处理版本（支持矩阵输入）

```python
def softmax_batch(X, axis=-1):
    """
    支持批量处理的Softmax函数
    
    参数:
    X: 输入向量或矩阵
    axis: 沿着哪个轴计算softmax
    
    返回:
    Softmax计算结果
    """
    # 数值稳定性处理
    X_shifted = X - np.max(X, axis=axis, keepdims=True)
    
    # 计算指数
    exp_values = np.exp(X_shifted)
    
    # 计算softmax
    softmax_output = exp_values / np.sum(exp_values, axis=axis, keepdims=True)
    
    return softmax_output

# 测试批量处理
print("\n=== 批量处理测试 ===")
X_batch = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("输入矩阵:")
print(X_batch)
print("每行Softmax结果:")
print(softmax_batch(X_batch, axis=1))
print("每行总和:", np.sum(softmax_batch(X_batch, axis=1), axis=1))
```

## 关键改进点

1. **数值稳定性**：通过减去最大值防止指数计算时出现溢出
2. **向量化操作**：使用numpy的向量化操作提高效率
3. **批量支持**：可以处理单个向量或批量数据
4. **轴参数**：支持指定计算softmax的维度

## 数学公式

Softmax函数的数学表达式为：
$$
\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_{j=1}^{n} e^{x_j}}
$$

数值稳定版本的公式为：
$$
\text{softmax}(x_i) = \frac{e^{x_i - \max(\mathbf{x})}}{\sum_{j=1}^{n} e^{x_j - \max(\mathbf{x})}}
$$

这样的实现既保持了数学正确性，又具备了工程实用性。

In [3]:
# softmax 公式，程序实现
import numpy as np
import math

def softmax(X):
    # 求指数e
    exp_values = [math.exp(i) for i in X-max(X)]
    print(exp_values)
    s = sum(exp_values)
    print(s)
    v = [i/s for i in exp_values]
    print(v)
    print(sum(v))



X = [2, 1, 3, 5, 6]
X = np.array(X)
print(X)

softmax(X)

[2 1 3 5 6]
[0.01831563888873418, 0.006737946999085467, 0.049787068367863944, 0.36787944117144233, 1.0]
1.442720095427126
[0.01269521298468621, 0.004670307858358802, 0.03450916676468985, 0.2549901691516464, 0.6931351432406186]
0.9999999999999999


In [4]:
# softmax 公式，程序实现
import numpy as np
import random
import torch
import math

def softmax(X):
    # 稳定性数值处理：减去最大值防止指数溢出
    X_shifted = X -np.max(X)

    # 计算指数
    exp_values = np.exp(X_shifted)

    # 计算softmax
    softmax_output = exp_values / np.sum(exp_values)
    print(softmax_output)

    return softmax_output


# 测试
X = [2, 1, 3, 5, 6]
print(X)

result = softmax(X)
print("Softmax结果：", result)
print("结果总和：", np.sum(result)) # 最终结果为1


# 验证数值稳定性
# large_X = torch.randn(500, 1000, 10)
# large_X = np.random(500, 1000, 10)
large_X = np.random.randint(500, 1000, 10)
print(large_X)

result = softmax(large_X)
print("Softmax结果：", result)
print("结果总和：", np.sum(result)) # 最终结果为1



[2, 1, 3, 5, 6]
[0.01269521 0.00467031 0.03450917 0.25499017 0.69313514]
Softmax结果： [0.01269521 0.00467031 0.03450917 0.25499017 0.69313514]
结果总和： 0.9999999999999999
[897 941 537 615 739 560 952 670 788 886]
[1.29955972e-024 1.67014218e-005 5.85845039e-181 4.39291040e-147
 3.12800977e-093 5.70894476e-171 9.99983299e-001 3.38025022e-123
 5.96619872e-072 2.17048576e-029]
Softmax结果： [1.29955972e-024 1.67014218e-005 5.85845039e-181 4.39291040e-147
 3.12800977e-093 5.70894476e-171 9.99983299e-001 3.38025022e-123
 5.96619872e-072 2.17048576e-029]
结果总和： 1.0000000000000002


In [ ]:
import torch
result = torch.tensor(1) # 创建一个一维张量

result = torch.tensor(1) + torch.tensor(2.0) # 张量相加
print(result)

print(torch.zeros(10))
print(torch.tensor(12.))
t2 = torch.arange(12).reshape(4,3)

print(t2[[2,1],[0,2]])

"""
chunk 函数
1.功能
  用于将给定的张量（tensor）沿着指定的维度（dim）分割成指定数量（chunks）的小块（chunks）。这个函数在需要将数据批处理成更小的子集以便并行处理或分批处理时非常有用。
2.基本语法
chunk(input, chunks, dim)

"""
print(torch.chunk(t2, 4, 0))

"""
我们可以把shape的返回结果看成一个序列，代表着各张量维度的信息，第一个数字3代表行，即向量数，第二个数字4代表列，即每个向量中的标量数。
深入理解：t2是由3个一维张量组成，并且每个一维张量都包含四个元素。

"""

t2 = torch.zeros((3, 4)) # 里面加(3, 4)可以直接转换成张量
print(t2)
t2.shape # .shape 查看张量形状

tensor(3.)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor(12.)
tensor([6, 5])
(tensor([[0, 1, 2]]), tensor([[3, 4, 5]]), tensor([[6, 7, 8]]), tensor([[ 9, 10, 11]]))
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


torch.Size([3, 4])

In [ ]:
#!/usr/bin/env python
# -*- coding:utf-8 -*-
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import matplotlib.pyplot as plt
# MNIST_data指的是存放数据的文件夹路径，one_hot=True 为采用one_hot的编码方式编码标签
mnist = input_data.read_data_sets('../datasets/MNIST_data/', one_hot=True)
# load data
train_X = mnist.train.images
train_Y = mnist.train.labels
print(train_X.shape, train_Y.shape)   # 输出训练集样本和标签的大小

AttributeError: 'builtin_function_or_method' object has no attribute 'tensor'