In [22]:
import numpy as np
from scipy.linalg import circulant # 循环矩阵

n = 3
p = np.random.rand(n)

print(p)
c = circulant(p) # 
print(c)


[0.57220795 0.61218328 0.84399542]
[[0.57220795 0.84399542 0.61218328]
 [0.61218328 0.57220795 0.84399542]
 [0.84399542 0.61218328 0.57220795]]


In [23]:
_, eigvecs = np.linalg.eig(c) # 特征值和特征向量
print(eigvecs)

[[-0.57735027+0.j  -0.28867513-0.5j -0.28867513+0.5j]
 [-0.57735027+0.j   0.57735027+0.j   0.57735027-0.j ]
 [-0.57735027+0.j  -0.28867513+0.5j -0.28867513-0.5j]]
